sudo: false
language: node_js
node_js: "node"
# Skip "npm install" since "npm run build" takes care of it below
install: true
before_script:
- cd ..
- git clone https://github.com/superpowers/superpowers-core.git
- cd superpowers-core
- mkdir systems
- mv ../superpowers-web systems/web
- ls -l systems
cache:
  directories:
  - node_modules
script:
- npm run build
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/44f5607466509af53a93
    on_success: change
    on_failure: always
    on_start: never
before_deploy:
- npm run package web
deploy:
  provider: releases
  api_key:
    secure: KTJ4Vmp/7Z7U722mwALwqP3KKPKw1eljnERi+DY1UAMqD08An0mVO8INFPvCcGehGUzhVlrsIOVi/cGi3g93p7S4wOBoPZahFcdiFz3vBM2LVhPJLd3aJ51NvMq6Pi7aCqPLCLurZ7FM8uT+xxzofaoxZzUEvxsBiT18NNN8C0Q5SPpAMTdDcvT2LzbeRkXFA7du/4Lu3tR5t8PUfhEyvWRZybT2bCtptPYwZsspjb7g4+Lf9FfIy/xzIcoqjrTcVCHK11C+d1pY/Gl+TOAoebgdxY2kNtWEO2K0sfuIDJogckaJVFB9G7SQPwkp6FP6KoNWZMwKh2jdH0w12RZgMufKYeUVukVEJ5rLe7tBphSWbV8673Qefm7/Iq7bnRLQjwzeHhN7B/AcmrDwjGPcahBAgzery/enmJZWMz5X4FabrOlAULWa8Ek6AxyiNq4MRyn2TrnEcZCf2Krb21J76iE9RKGV6o3N6WqBHWC6uXy7DefT1LvaaD82JLxnSw053O6n5pEnXp9HhfbdUJVg6cYAdrEqNrRG3ItxPx6Ye3ZsUL8+uOC6TvBKemxwuWM+h7Cb3SLHlJlxG+V4eqym/4gBYPBtHZzgwO+DvwrFajzJHXQ4KtuOofOAHgcs57VAyb+IrZdx2ZboRGACOciHGrOo8k0O0GovD6vQsFqV2sA=
  file_glob: true
  file: "packages/superpowers-web-*.zip"
  skip_cleanup: true
  on:
    repo: superpowers/superpowers-web
    tags: true
